### PR TITLE
MC-tasks

### PR DESCRIPTION
**Pull request by MattCrook**
git fetch --all 
git checkout MC-tasks

Should display tasks as cards. 

ToDo:
Sort by decending order.
Handle the check box functionality. (hide card from user)

### CODE REVIEW

**Comment by keithrpotempa** [comment]
Important fixes:
- Deleting works, but it doesn't re-render the DOM. Maybe call the function that gets/sets your task state after the api call?
- Edit saves and mostly works, but I can't edit the task's name

For future updates:
- I've got a rainbow button and a baby blue box around my chat form -- perhaps your CSS could be more specifically targeting your elements?
- I'm seeing all the tasks, aren't we supposed to only see the tasks that match my userId?

**Review by kurtkrafft1 — APPROVED** [review]
👍

**Review by Iandonmorgan — APPROVED** [review]
👍

**Review by keithrpotempa — APPROVED** [review]
👍 👍 👍 
👍 💯 👍 
👍 👍 👍

**Pull request merged**
